### ISSUE TITLE
Is there a potential race condition in IgnoreErrorStructuredTaskScope?

### ISSUE THREAD

**Issue by Flowdalic** [forax/loom-fiber#7]
Hi Rémi,

first of all, I'd like to thank you for the loom examples.

However, I wonder if there is a race condition in `IgnoreErrorStructuredTaskScope`. More precisely, I asked myself if

https://github.com/forax/loom-fiber/blob/6a875be5793571a88d75f48f315d55e5e69662e2/src/main/java/fr/umlv/loom/example/_14_adhoc_scope.java#L43

could not be called before the `future` is put into the map in

https://github.com/forax/loom-fiber/blob/6a875be5793571a88d75f48f315d55e5e69662e2/src/main/java/fr/umlv/loom/example/_14_adhoc_scope.java#L35

I do not find anything that would prevent the `handleComplete(Future<T>)` callback to be invoked and completed after the `scope.fork()` but before `future` is put into the map. In that case, the callback would not find the future in the map.

What am I missing?

**Comment by forax** [comment]
oops, you are right, i've changed the example to a more useful one.

This demonstrate that the API is not good enough because it requires too many eyeballs to write correct code with it.
